DATA	SEGMENT
NUMH1	DW	0005H	;被加数1的高位
NUML1	DW	2222H	;被加数1的低位
NUMH2	DW	0003H	;被加数2的高位
NUML2	DW	0EEEEH  ;被加数2的低位
RESH	DW	?	;结果的高位
RESL	DW	?	;结果的低位
DATA	ENDS

CODE	SEGMENT
	ASSUME CS:CODE,DS:DATA
START:MOV AX,DATA
	MOV DS,AX
	MOV AX,NUML1
	ADD AX,NUML2;低位相加
	MOV RESL,AX;存储低位结果
	MOV AX,NUMH1
	ADC AX,NUMH2;高位和CF相加，注意可能有进位，所以用带进位的加法
	MOV RESH,AX	;存储高位结果
	
	MOV	AH,4CH
	INT	21H
CODE	ENDS
END	START